rewrite ^$ /;
location ~ ^/$ {
  default_type text/plain;
  return 200 "This is where Continuwuity is installed.";
}

location /_matrix {
  proxy_pass http://127.0.0.1:__PORT__;
  proxy_set_header X-Real-IP  $remote_addr;
  proxy_set_header Host  $host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_read_timeout 600;
  client_max_body_size 100M;
  more_set_headers "Access-Control-Allow-Origin: *";
}

# Continuwuity's integrated account management interface for OAuth-compatible
# clients. Public by default (matches upstream recommendation).
location /_continuwuity {
  proxy_pass http://127.0.0.1:__PORT__;
  proxy_set_header X-Real-IP  $remote_addr;
  proxy_set_header Host  $host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_read_timeout 600;
  client_max_body_size 100M;
}
