# .well-known/matrix delegation, served on the server_name domain.
# Installed as /etc/nginx/conf.d/$server_name.d/${app}_server_name.conf
# (only when $server_name is a domain managed by this YunoHost instance).
location = /.well-known/matrix/server {
    return 200 '{"m.server": "__DOMAIN__:443"}';
    add_header Content-Type application/json;
    add_header Access-Control-Allow-Origin '*';
}

location = /.well-known/matrix/client {
    return 200 '{
        "m.homeserver": { "base_url": "https://__DOMAIN__" },
        "org.matrix.msc3575.proxy": { "url": "https://__DOMAIN__" }
    }';
    add_header Content-Type application/json;
    add_header Access-Control-Allow-Origin '*';
}

location = /.well-known/matrix/support {
    return 200 '{
        "contacts": []
    }';
    add_header Content-Type application/json;
    add_header Access-Control-Allow-Origin '*';
}
